import React from "react";
import JavaContent from "../../JavaContent";
import style from "./MyStyle.module.css";
import { Container, Row } from "react-bootstrap";

export default function JavaHistory() {
  return (
    <div>
      <JavaContent />
      <div style={{ marginTop: "40px" }}>
        <Container className={style.centered}>
          <Row>
            <div className={style.contentHeader}>History of Java</div>
            <div className={style.contentBody}>
              James Gosling pioneered Java in June 1991 as a project called
              ‘Oak.’ Gosling aimed to develop a virtual machine and language
              with a well-known notation like C, but with more precision and
              simplicity than C/C++. In 1995, Java 1.0 was the first public
              execution. It pledged ‘Write Once, Run Anywhere’ on popular
              platforms with free runtimes. It was very safe and configurable
              with security that restricted network and file access. In a stable
              ‘applet’ setup, the significant web browsers soon implemented it
              in their standard settings.<br/><br/> In 1997, Sun reached out to the
              ISO/IEC JTC1 and then Ecma International to formalize Java, but
              they quickly withdrew. Java continues to be a de facto proprietary
              standard regulated by the Java Community Process. With the revenue
              generated by new vision such as the Java Enterprise Framework, Sun
              made several Java implementations free of charge. The critical
              difference is that the compiler is not present in the JRE, which
              differentiates between its Software Development Kit (SDK) and JRE
              (JRE).<br/><br/> On 13 November 2006, Sun launched a considerable amount of
              Java in the GNU General Public License as free and open-source
              software (GPL) (GPL). On 8 May 2007, Sun completed the process by
              releasing a fully accessible, all free and open-source Java’s core
              code, except for a small portion of the code that Sun did not
              copyright.
            </div>
          </Row>
        </Container>
        <br />
      </div>
    </div>
  );
}
